name: "Terraform"

on:
  push:
    branches:
      - main
      - "users/**"
  pull_request:
    branches:
      - main
      - "users/**"
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: 'Type YES to confirm destroy'
        required: true
        default: 'NO'

jobs:
  terraform:
    name: "dev"
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
    runs-on: ubuntu-latest
    environment: dev

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "Terraform Format"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.5.0
          tf_actions_subcommand: "fmt"
          tf_actions_working_dir: "./terraform"

      - name: "Terraform Init"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.5.0
          tf_actions_subcommand: "init"
          tf_actions_working_dir: "./terraform"

      - name: "Terraform Validate"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.5.0
          tf_actions_subcommand: "validate"
          tf_actions_working_dir: "./terraform"

      - name: "Terraform Plan"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.5.0
          tf_actions_subcommand: "plan"
          tf_actions_working_dir: "./terraform"

      - name: Terraform Apply
        if: startsWith(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/heads/users/')
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.5.0
          tf_actions_subcommand: "apply"
          tf_actions_working_dir: "./terraform"

  destroy:
    name: 'Terraform Destroy'
    needs: terraform
    runs-on: ubuntu-latest
    environment: destroy
    if: startsWith(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/heads/users/')
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: ./terraform
